import type { Project } from "@/types/project"

export const seedProjects: Project[] = [
  {
    id: "1",
    name: "Website Redesign",
    status: "active",
    startDate: "2024-01-15",
    endDate: "2024-03-01",
    owner: "Alice Johnson",
    budget: { current: 50000, spent: 15000 },
    tasks: [
      {
        id: "1",
        title: "Design mockups",
        status: "completed",
        assignee: "Bob Smith",
        dueDate: "2024-01-30",
        weight: 3,
        category: "Design",
      },
      {
        id: "2",
        title: "Frontend development",
        status: "in-progress",
        assignee: "Carol White",
        dueDate: "2024-02-15",
        weight: 5,
        category: "Development",
      },
    ],
  },
  {
    id: "2",
    name: "Mobile App",
    status: "idea",
    startDate: "2024-02-01",
    endDate: "2024-06-15",
    owner: "Bob Smith",
    budget: { current: 75000, spent: 5000 },
    tasks: [
      {
        id: "3",
        title: "Market research",
        status: "todo",
        assignee: "Dave Brown",
        dueDate: "2024-02-10",
        weight: 2,
        category: "Research",
      },
    ],
  },
  {
    id: "3",
    name: "API Refactor",
    status: "completed",
    startDate: "2023-11-01",
    endDate: "2024-01-10",
    owner: "Carol White",
    budget: { current: 30000, spent: 28000 },
    tasks: [
      {
        id: "4",
        title: "Database optimization",
        status: "completed",
        assignee: "Alice Johnson",
        dueDate: "2023-12-01",
        weight: 4,
        category: "Backend",
      },
    ],
  },
  {
    id: "4",
    name: "E-commerce Platform",
    status: "active",
    startDate: "2024-01-20",
    endDate: "2024-05-30",
    owner: "David Wilson",
    budget: { current: 120000, spent: 35000 },
    tasks: [
      {
        id: "5",
        title: "Payment integration",
        status: "in-progress",
        assignee: "Emma Davis",
        dueDate: "2024-03-01",
        weight: 5,
        category: "Development",
      },
      {
        id: "6",
        title: "Product catalog",
        status: "completed",
        assignee: "Frank Miller",
        dueDate: "2024-02-15",
        weight: 3,
        category: "Development",
      },
    ],
  },
  {
    id: "5",
    name: "Data Analytics Dashboard",
    status: "paused",
    startDate: "2023-12-01",
    endDate: "2024-04-01",
    owner: "Emma Davis",
    budget: { current: 80000, spent: 45000 },
    tasks: [
      {
        id: "7",
        title: "Chart components",
        status: "blocked",
        assignee: "Grace Lee",
        dueDate: "2024-01-20",
        weight: 4,
        category: "Frontend",
      },
    ],
  },
  {
    id: "6",
    name: "Customer Support Portal",
    status: "completed",
    startDate: "2023-09-01",
    endDate: "2023-12-15",
    owner: "Frank Miller",
    budget: { current: 45000, spent: 42000 },
    tasks: [
      {
        id: "8",
        title: "Ticket system",
        status: "completed",
        assignee: "Henry Clark",
        dueDate: "2023-11-01",
        weight: 5,
        category: "Backend",
      },
    ],
  },
  {
    id: "7",
    name: "Marketing Website",
    status: "active",
    startDate: "2024-02-01",
    endDate: "2024-04-15",
    owner: "Grace Lee",
    budget: { current: 35000, spent: 12000 },
    tasks: [
      {
        id: "9",
        title: "SEO optimization",
        status: "todo",
        assignee: "Ivan Rodriguez",
        dueDate: "2024-03-15",
        weight: 3,
        category: "Marketing",
      },
    ],
  },
  {
    id: "8",
    name: "Inventory Management",
    status: "idea",
    startDate: "2024-03-01",
    endDate: "2024-07-01",
    owner: "Henry Clark",
    budget: { current: 95000, spent: 0 },
    tasks: [],
  },
  {
    id: "9",
    name: "HR Management System",
    status: "active",
    startDate: "2024-01-10",
    endDate: "2024-06-01",
    owner: "Ivan Rodriguez",
    budget: { current: 110000, spent: 25000 },
    tasks: [
      {
        id: "10",
        title: "Employee onboarding",
        status: "in-progress",
        assignee: "Julia Anderson",
        dueDate: "2024-03-01",
        weight: 4,
        category: "Development",
      },
    ],
  },
  {
    id: "10",
    name: "Security Audit",
    status: "completed",
    startDate: "2023-10-01",
    endDate: "2023-11-30",
    owner: "Julia Anderson",
    budget: { current: 25000, spent: 24000 },
    tasks: [
      {
        id: "11",
        title: "Vulnerability assessment",
        status: "completed",
        assignee: "Kevin Thompson",
        dueDate: "2023-11-15",
        weight: 5,
        category: "Security",
      },
    ],
  },
  {
    id: "11",
    name: "Cloud Migration",
    status: "active",
    startDate: "2024-01-05",
    endDate: "2024-04-30",
    owner: "Kevin Thompson",
    budget: { current: 85000, spent: 32000 },
    tasks: [
      {
        id: "12",
        title: "Infrastructure assessment",
        status: "completed",
        assignee: "Laura Wilson",
        dueDate: "2024-01-20",
        weight: 3,
        category: "Infrastructure",
      },
      {
        id: "13",
        title: "Migration planning",
        status: "in-progress",
        assignee: "Mike Brown",
        dueDate: "2024-02-28",
        weight: 4,
        category: "Infrastructure",
      },
    ],
  },
  {
    id: "12",
    name: "CRM Integration",
    status: "paused",
    startDate: "2023-11-15",
    endDate: "2024-02-29",
    owner: "Laura Wilson",
    budget: { current: 65000, spent: 40000 },
    tasks: [
      {
        id: "14",
        title: "API development",
        status: "blocked",
        assignee: "Nancy Davis",
        dueDate: "2024-01-15",
        weight: 5,
        category: "Backend",
      },
    ],
  },
  {
    id: "13",
    name: "Performance Optimization",
    status: "completed",
    startDate: "2023-08-01",
    endDate: "2023-10-15",
    owner: "Mike Brown",
    budget: { current: 40000, spent: 38000 },
    tasks: [
      {
        id: "15",
        title: "Code profiling",
        status: "completed",
        assignee: "Oliver Smith",
        dueDate: "2023-09-01",
        weight: 3,
        category: "Development",
      },
      {
        id: "16",
        title: "Database tuning",
        status: "completed",
        assignee: "Paula Green",
        dueDate: "2023-09-30",
        weight: 4,
        category: "Backend",
      },
    ],
  },
  {
    id: "14",
    name: "Social Media Integration",
    status: "idea",
    startDate: "2024-04-01",
    endDate: "2024-06-30",
    owner: "Nancy Davis",
    budget: { current: 55000, spent: 0 },
    tasks: [],
  },
  {
    id: "15",
    name: "Quality Assurance Framework",
    status: "active",
    startDate: "2024-01-20",
    endDate: "2024-05-15",
    owner: "Oliver Smith",
    budget: { current: 70000, spent: 20000 },
    tasks: [
      {
        id: "17",
        title: "Test automation setup",
        status: "in-progress",
        assignee: "Quinn Johnson",
        dueDate: "2024-03-10",
        weight: 5,
        category: "Testing",
      },
      {
        id: "18",
        title: "Documentation",
        status: "todo",
        assignee: "Rachel Martinez",
        dueDate: "2024-04-01",
        weight: 2,
        category: "Documentation",
      },
    ],
  },
  {
    id: "16",
    name: "Backup & Recovery System",
    status: "completed",
    startDate: "2023-09-15",
    endDate: "2023-12-01",
    owner: "Paula Green",
    budget: { current: 30000, spent: 29500 },
    tasks: [
      {
        id: "19",
        title: "Backup strategy",
        status: "completed",
        assignee: "Steve Anderson",
        dueDate: "2023-10-15",
        weight: 4,
        category: "Infrastructure",
      },
    ],
  },
  {
    id: "17",
    name: "User Authentication Upgrade",
    status: "active",
    startDate: "2024-02-05",
    endDate: "2024-04-20",
    owner: "Quinn Johnson",
    budget: { current: 45000, spent: 15000 },
    tasks: [
      {
        id: "20",
        title: "OAuth implementation",
        status: "in-progress",
        assignee: "Tina Williams",
        dueDate: "2024-03-15",
        weight: 4,
        category: "Security",
      },
      {
        id: "21",
        title: "Two-factor auth",
        status: "todo",
        assignee: "Uma Patel",
        dueDate: "2024-04-10",
        weight: 3,
        category: "Security",
      },
    ],
  },
  {
    id: "18",
    name: "Reporting Dashboard",
    status: "paused",
    startDate: "2023-12-10",
    endDate: "2024-03-31",
    owner: "Rachel Martinez",
    budget: { current: 60000, spent: 35000 },
    tasks: [
      {
        id: "22",
        title: "Data visualization",
        status: "blocked",
        assignee: "Victor Chen",
        dueDate: "2024-02-15",
        weight: 5,
        category: "Frontend",
      },
    ],
  },
  {
    id: "19",
    name: "Content Management System",
    status: "idea",
    startDate: "2024-05-01",
    endDate: "2024-08-30",
    owner: "Steve Anderson",
    budget: { current: 90000, spent: 0 },
    tasks: [],
  },
  {
    id: "20",
    name: "API Documentation Portal",
    status: "completed",
    startDate: "2023-07-01",
    endDate: "2023-09-30",
    owner: "Tina Williams",
    budget: { current: 35000, spent: 33000 },
    tasks: [
      {
        id: "23",
        title: "Interactive docs",
        status: "completed",
        assignee: "William Davis",
        dueDate: "2023-08-15",
        weight: 4,
        category: "Documentation",
      },
    ],
  },
  {
    id: "21",
    name: "Microservices Architecture",
    status: "active",
    startDate: "2024-01-08",
    endDate: "2024-07-15",
    owner: "Uma Patel",
    budget: { current: 150000, spent: 45000 },
    tasks: [
      {
        id: "24",
        title: "Service decomposition",
        status: "in-progress",
        assignee: "Xavier Rodriguez",
        dueDate: "2024-04-01",
        weight: 5,
        category: "Architecture",
      },
      {
        id: "25",
        title: "Container orchestration",
        status: "todo",
        assignee: "Yara Kim",
        dueDate: "2024-05-15",
        weight: 4,
        category: "Infrastructure",
      },
    ],
  },
  {
    id: "22",
    name: "Notification Service",
    status: "active",
    startDate: "2024-02-10",
    endDate: "2024-04-25",
    owner: "Victor Chen",
    budget: { current: 40000, spent: 18000 },
    tasks: [
      {
        id: "26",
        title: "Email templates",
        status: "completed",
        assignee: "Zoe Thompson",
        dueDate: "2024-02-28",
        weight: 2,
        category: "Design",
      },
      {
        id: "27",
        title: "Push notifications",
        status: "in-progress",
        assignee: "Adam Wilson",
        dueDate: "2024-03-20",
        weight: 3,
        category: "Development",
      },
    ],
  },
  {
    id: "23",
    name: "Data Warehouse Migration",
    status: "paused",
    startDate: "2023-10-15",
    endDate: "2024-01-31",
    owner: "William Davis",
    budget: { current: 120000, spent: 80000 },
    tasks: [
      {
        id: "28",
        title: "ETL pipeline",
        status: "blocked",
        assignee: "Betty Johnson",
        dueDate: "2024-01-15",
        weight: 5,
        category: "Data",
      },
    ],
  },
  {
    id: "24",
    name: "Mobile App Redesign",
    status: "idea",
    startDate: "2024-06-01",
    endDate: "2024-09-30",
    owner: "Xavier Rodriguez",
    budget: { current: 100000, spent: 0 },
    tasks: [],
  },
  {
    id: "25",
    name: "Compliance Automation",
    status: "completed",
    startDate: "2023-06-01",
    endDate: "2023-08-31",
    owner: "Yara Kim",
    budget: { current: 50000, spent: 48000 },
    tasks: [
      {
        id: "29",
        title: "GDPR compliance",
        status: "completed",
        assignee: "Carlos Martinez",
        dueDate: "2023-07-15",
        weight: 4,
        category: "Compliance",
      },
      {
        id: "30",
        title: "Audit trail",
        status: "completed",
        assignee: "Diana Lee",
        dueDate: "2023-08-15",
        weight: 3,
        category: "Compliance",
      },
    ],
  },
  {
    id: "26",
    name: "Search Engine Optimization",
    status: "active",
    startDate: "2024-01-25",
    endDate: "2024-05-01",
    owner: "Zoe Thompson",
    budget: { current: 25000, spent: 8000 },
    tasks: [
      {
        id: "31",
        title: "Keyword research",
        status: "completed",
        assignee: "Eric Brown",
        dueDate: "2024-02-10",
        weight: 2,
        category: "Marketing",
      },
      {
        id: "32",
        title: "Content optimization",
        status: "in-progress",
        assignee: "Fiona Davis",
        dueDate: "2024-03-31",
        weight: 3,
        category: "Content",
      },
    ],
  },
  {
    id: "27",
    name: "Real-time Analytics",
    status: "active",
    startDate: "2024-02-15",
    endDate: "2024-06-15",
    owner: "Adam Wilson",
    budget: { current: 95000, spent: 30000 },
    tasks: [
      {
        id: "33",
        title: "Stream processing",
        status: "in-progress",
        assignee: "George Wilson",
        dueDate: "2024-04-01",
        weight: 5,
        category: "Data",
      },
      {
        id: "34",
        title: "Real-time dashboards",
        status: "todo",
        assignee: "Helen Smith",
        dueDate: "2024-05-15",
        weight: 4,
        category: "Frontend",
      },
    ],
  },
  {
    id: "28",
    name: "DevOps Pipeline Enhancement",
    status: "completed",
    startDate: "2023-08-15",
    endDate: "2023-11-15",
    owner: "Betty Johnson",
    budget: { current: 60000, spent: 57000 },
    tasks: [
      {
        id: "35",
        title: "CI/CD automation",
        status: "completed",
        assignee: "Ian Rodriguez",
        dueDate: "2023-10-01",
        weight: 4,
        category: "DevOps",
      },
      {
        id: "36",
        title: "Monitoring setup",
        status: "completed",
        assignee: "Jenna Kim",
        dueDate: "2023-11-01",
        weight: 3,
        category: "Infrastructure",
      },
    ],
  },
  {
    id: "29",
    name: "Chatbot Integration",
    status: "idea",
    startDate: "2024-07-01",
    endDate: "2024-10-15",
    owner: "Carlos Martinez",
    budget: { current: 75000, spent: 0 },
    tasks: [],
  },
  {
    id: "30",
    name: "Legacy System Modernization",
    status: "paused",
    startDate: "2023-09-01",
    endDate: "2024-06-30",
    owner: "Diana Lee",
    budget: { current: 200000, spent: 120000 },
    tasks: [
      {
        id: "37",
        title: "Code refactoring",
        status: "blocked",
        assignee: "Kevin Anderson",
        dueDate: "2024-03-01",
        weight: 5,
        category: "Development",
      },
      {
        id: "38",
        title: "Database migration",
        status: "blocked",
        assignee: "Lisa Chen",
        dueDate: "2024-04-15",
        weight: 5,
        category: "Backend",
      },
    ],
  },
  {
    id: "31",
    name: "User Experience Research",
    status: "active",
    startDate: "2024-01-30",
    endDate: "2024-04-30",
    owner: "Eric Brown",
    budget: { current: 30000, spent: 12000 },
    tasks: [
      {
        id: "39",
        title: "User interviews",
        status: "in-progress",
        assignee: "Maria Garcia",
        dueDate: "2024-03-15",
        weight: 3,
        category: "Research",
      },
      {
        id: "40",
        title: "Usability testing",
        status: "todo",
        assignee: "Nathan Thompson",
        dueDate: "2024-04-15",
        weight: 4,
        category: "Research",
      },
    ],
  },
  {
    id: "32",
    name: "Payment Gateway Integration",
    status: "completed",
    startDate: "2023-05-01",
    endDate: "2023-07-15",
    owner: "Fiona Davis",
    budget: { current: 55000, spent: 52000 },
    tasks: [
      {
        id: "41",
        title: "Stripe integration",
        status: "completed",
        assignee: "Oscar Martinez",
        dueDate: "2023-06-15",
        weight: 4,
        category: "Development",
      },
      {
        id: "42",
        title: "PayPal integration",
        status: "completed",
        assignee: "Penny Wilson",
        dueDate: "2023-07-01",
        weight: 3,
        category: "Development",
      },
    ],
  },
  {
    id: "33",
    name: "Internationalization Support",
    status: "active",
    startDate: "2024-02-20",
    endDate: "2024-06-01",
    owner: "George Wilson",
    budget: { current: 65000, spent: 22000 },
    tasks: [
      {
        id: "43",
        title: "Translation framework",
        status: "in-progress",
        assignee: "Quinn Davis",
        dueDate: "2024-03-30",
        weight: 4,
        category: "Development",
      },
      {
        id: "44",
        title: "Locale support",
        status: "todo",
        assignee: "Rosa Kim",
        dueDate: "2024-05-15",
        weight: 3,
        category: "Development",
      },
    ],
  },
  {
    id: "34",
    name: "A/B Testing Platform",
    status: "idea",
    startDate: "2024-08-01",
    endDate: "2024-11-30",
    owner: "Helen Smith",
    budget: { current: 80000, spent: 0 },
    tasks: [],
  },
  {
    id: "35",
    name: "Database Optimization",
    status: "completed",
    startDate: "2023-04-01",
    endDate: "2023-06-15",
    owner: "Ian Rodriguez",
    budget: { current: 40000, spent: 38500 },
    tasks: [
      {
        id: "45",
        title: "Query optimization",
        status: "completed",
        assignee: "Sam Johnson",
        dueDate: "2023-05-01",
        weight: 4,
        category: "Backend",
      },
      {
        id: "46",
        title: "Index optimization",
        status: "completed",
        assignee: "Tara Lee",
        dueDate: "2023-06-01",
        weight: 3,
        category: "Backend",
      },
    ],
  },
  {
    id: "36",
    name: "Machine Learning Pipeline",
    status: "active",
    startDate: "2024-01-15",
    endDate: "2024-08-01",
    owner: "Jenna Kim",
    budget: { current: 180000, spent: 60000 },
    tasks: [
      {
        id: "47",
        title: "Data preprocessing",
        status: "completed",
        assignee: "Uma Rodriguez",
        dueDate: "2024-02-28",
        weight: 4,
        category: "Data",
      },
      {
        id: "48",
        title: "Model training",
        status: "in-progress",
        assignee: "Victor Martinez",
        dueDate: "2024-05-01",
        weight: 5,
        category: "ML",
      },
      {
        id: "49",
        title: "Model deployment",
        status: "todo",
        assignee: "Wendy Chen",
        dueDate: "2024-07-15",
        weight: 4,
        category: "ML",
      },
    ],
  },
  {
    id: "37",
    name: "Error Monitoring System",
    status: "paused",
    startDate: "2023-11-20",
    endDate: "2024-02-29",
    owner: "Kevin Anderson",
    budget: { current: 35000, spent: 20000 },
    tasks: [
      {
        id: "50",
        title: "Error tracking setup",
        status: "blocked",
        assignee: "Xander Wilson",
        dueDate: "2024-01-15",
        weight: 3,
        category: "Infrastructure",
      },
    ],
  },
  {
    id: "38",
    name: "Workflow Automation",
    status: "active",
    startDate: "2024-02-25",
    endDate: "2024-05-31",
    owner: "Lisa Chen",
    budget: { current: 70000, spent: 25000 },
    tasks: [
      {
        id: "51",
        title: "Process mapping",
        status: "completed",
        assignee: "Yuki Thompson",
        dueDate: "2024-03-10",
        weight: 2,
        category: "Analysis",
      },
      {
        id: "52",
        title: "Automation scripts",
        status: "in-progress",
        assignee: "Zara Davis",
        dueDate: "2024-04-30",
        weight: 4,
        category: "Development",
      },
    ],
  },
  {
    id: "39",
    name: "Customer Feedback Portal",
    status: "idea",
    startDate: "2024-09-01",
    endDate: "2024-12-15",
    owner: "Maria Garcia",
    budget: { current: 45000, spent: 0 },
    tasks: [],
  },
  {
    id: "40",
    name: "Network Security Upgrade",
    status: "completed",
    startDate: "2023-03-01",
    endDate: "2023-05-31",
    owner: "Nathan Thompson",
    budget: { current: 85000, spent: 82000 },
    tasks: [
      {
        id: "53",
        title: "Firewall configuration",
        status: "completed",
        assignee: "Alice Rodriguez",
        dueDate: "2023-04-01",
        weight: 4,
        category: "Security",
      },
      {
        id: "54",
        title: "VPN setup",
        status: "completed",
        assignee: "Bob Kim",
        dueDate: "2023-05-15",
        weight: 3,
        category: "Security",
      },
      {
        id: "55",
        title: "Security audit",
        status: "completed",
        assignee: "Carol Martinez",
        dueDate: "2023-05-25",
        weight: 5,
        category: "Security",
      },
    ],
  },
]
